{{- range $secretName, $secretData := .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: {{ $secretData.type }}
data:
{{- range $key, $value := $secretData.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---
{{- end }}
