
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debezium.fullname" . }}
  labels:
    app: {{ include "debezium.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "debezium.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "debezium.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{.Values.image}}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /debezium/conf
              name: debezium-conf
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      volumes:
        - name: debezium-conf
          configMap:
            name: {{ include "debezium.fullname" . }}-config