apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "basic-objects.fullname" . }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "basic-objects.fullname" . }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ include "basic-objects.fullname" . }}-sa
    namespace: {{.Release.Namespace}}
