apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "basic-objects.fullname" . }}-sa
  labels:
    {{- include "basic-objects.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
