kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "confiape-app.fullname" . }}-debezium-config
data:
  application.properties: |
    debezium.sink.type=rabbitmq
    debezium.sink.rabbitmq.connection.host={{ include "confiape-app.fullname" . }}-rabbitmq.{{.Release.Namespace}}.svc
    debezium.sink.rabbitmq.connection.port=5672
    debezium.sink.rabbitmq.connection.username={{.Values.rabbitmq.username}}
    debezium.sink.rabbitmq.connection.password={{.Values.rabbitmq.password}}
    debezium.sink.rabbitmq.connection.virtual.host=/
    debezium.sink.rabbitmq.ackTimeout=3000
    debezium.sink.rabbitmq.exchange={{.Values.debezium.rabbitmqExchange}}
    debezium.sink.rabbitmq.routingKey={{.Values.debezium.rabbitmqRoutingKey}}

    debezium.source.connector.class=io.debezium.connector.sqlserver.SqlServerConnector
    debezium.source.database.hostname={{.Values.debezium.sqlServerHost}}
    debezium.source.database.port={{.Values.debezium.sqlServerPort}}
    debezium.source.database.user={{.Values.debezium.sqlServerUser}}
    debezium.source.database.password={{.Values.debezium.sqlServerPassword}}
    debezium.source.database.names={{.Values.debezium.sqlServerDbName}}
    debezium.source.database.trustServerCertificate=true

    debezium.source.event.processing.failure.handling.mode=ignore
    include.schema.changes=false
    transforms.unwrap.delete.handling.mode=rewrite


    debezium.source.plugin.name=pgoutput
    debezium.source.offset.storage.file.filename=data/offsets.dat
    debezium.source.offset.flush.interval.ms=0
    debezium.source.database.allowPublicKeyRetrieval=true
    debezium.source.schema.history.internal=io.debezium.relational.history.MemorySchemaHistory

    debezium.source.table.include.list={{.Values.debezium.sqlserverIncludeTables}}
    debezium.source.topic.prefix={{.Values.debezium.rabbitmqTopicPrefix}}
    debezium.format.key=json
    debezium.format.value=json
    quarkus.log.console.json=false