{{- if .Values.rabbitmq.enabled}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "confiape-app.fullname" . }}-rabbitmq-secret
data:
  default_user.conf: {{ printf "default_user = %s\ndefault_pass = %s\n" .Values.rabbitmq.username .Values.rabbitmq.password | b64enc | trim }}
  host: {{ printf "%s-rabbitmq.%s.svc" (include "confiape-app.fullname" .) .Release.Namespace | b64enc | trim }}
  username: {{ .Values.rabbitmq.username | b64enc | trim }}
  password: {{ .Values.rabbitmq.password | b64enc | trim }}
  port: {{ "5672" | b64enc | trim }}
  provider: {{ "rabbitmq" | b64enc | trim }}
  type: {{ "rabbitmq" | b64enc | trim }}

type: Opaque

{{- end }}