apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ include "confiape-app.fullname" . }}-rabbitmq
spec:
  replicas: {{.Values.rabbitmq.replicas}}
  secretBackend:
    externalSecret:
      name: {{ include "confiape-app.fullname" . }}-rabbitmq-secret
  persistence:
    storageClassName: {{.Values.rabbitmq.storageClass}}
    storage: {{.Values.rabbitmq.storageSize}}
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ include "confiape-app.fullname" . }}-rabbitmq-queue
spec:
  name: {{ .Values.debezium.rabbitmqExchange}}
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: {{ include "confiape-app.fullname" . }}-rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: {{ include "confiape-app.fullname" . }}-rabbitmq-exchange
spec:
  name: {{ .Values.debezium.rabbitmqExchange}}
  type: direct
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: {{ include "confiape-app.fullname" . }}-rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ include "confiape-app.fullname" . }}-rabbitmq-binding
spec:
  source: {{ .Values.debezium.rabbitmqExchange}}
  destination:  {{ .Values.debezium.rabbitmqExchange}}
  destinationType: queue
  routingKey: {{ .Values.debezium.rabbitmqRoutingKey}}
  rabbitmqClusterReference:
    name: {{ include "confiape-app.fullname" . }}-rabbitmq