apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ include "confiape-app.fullname" . }}-rabbitmq
spec:
  replicas: {{.Values.rabbitmq.replicas}}
  secretBackend:
    externalSecret:
      name: {{ include "confiape-app.fullname" . }}-rabbitmq-secret
  persistence:
    storageClassName: {{.Values.rabbitmq.storageClass}}
    storage: {{.Values.rabbitmq.storageSize}}
