{{- range $storageName, $storage := .Values.storages }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $storageName }}
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
{{- end }}
