apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "job.fullname" . }}-{{.Release.Revision}}
  labels:
    app: {{ include "job.fullname" . }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "job.fullname" . }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

            {{- range $secretName, $secretNameValue := .Values.envSecrets }}
              {{- range $secretNameKey, $secretKey := $secretNameValue }}
            - name: {{ $secretKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $secretNameKey }}
              {{- end}}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}

      restartPolicy: Never

  backoffLimit: 3


