image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent

  tag: "2019-latest"

ACCEPT_EULA:
  value: "y"
MSSQL_PID:
  value: "Developer"
MSSQL_AGENT_ENABLED:
  value: "true"

secret:
  Name: secret
  key: mssqlPassword
containers:
  ports:
    containerPort: 1433

podAnnotations: { }

podSecurityContext:
  fsGroup: 10001

service:
  type: ClusterIP
  port: 1433

pvc:
  StorageClass: "local-path"
  userdbaccessMode: ReadWriteOnce
  userdbsize: 5Gi
  userlogaccessMode: ReadWriteOnce
  userlogsize: 5Gi
  tempdbaccessMode: ReadWriteOnce
  tempsize: 2Gi
  mssqldataaccessMode: ReadWriteOnce
  mssqldbsize: 2Gi
  backupaccessMode: ReadWriteOnce
  backupsize: 10Gi


