#storages:
#  my-storage-1:
#    capacity: 10Gi
#    accessModes:
#      - ReadWriteOnce
#    hostPath: /mnt/disks/vol1
#
#  my-storage-2:
#    capacity: 20Gi
#    accessModes:
#      - ReadWriteOnce
#    hostPath: /mnt/disks/vol2
