kind: Secret
apiVersion: v1
metadata:
  name: {{ include "rabbitmq.fullname" . }}-rabbitmq-secret
data:
  default_user.conf: {{ printf "default_user = %s\ndefault_pass = %s\n" .Values.username .Values.password | b64enc | trim }}
  host: {{ printf "%s-rabbitmq.%s.svc" (include "rabbitmq.fullname" .) .Release.Namespace | b64enc | trim }}
  username: {{ .Values.username | b64enc | trim }}
  password: {{ .Values.password | b64enc | trim }}
  port: {{ "5672" | b64enc | trim }}
  provider: {{ "rabbitmq" | b64enc | trim }}
  type: {{ "rabbitmq" | b64enc | trim }}
type: Opaque

