replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []


podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8000

readinessProbe:
  httpGet:
    path: /
    port: 8000

envFrom: []
env:
  a: b
envSecrets: {}
#envSecrets:
#  secretName:                        loan-secret:
#    secretNameKey: secretKey           sa_pass: ConnectionString__SAPassword



